// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/proto/metricsgsv.proto

package metricsgsv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsRec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MType         string                 `protobuf:"bytes,2,opt,name=MType,proto3" json:"MType,omitempty"`
	Delta         int64                  `protobuf:"zigzag64,3,opt,name=Delta,proto3" json:"Delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRec) Reset() {
	*x = MetricsRec{}
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRec) ProtoMessage() {}

func (x *MetricsRec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRec.ProtoReflect.Descriptor instead.
func (*MetricsRec) Descriptor() ([]byte, []int) {
	return file_internal_proto_metricsgsv_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsRec) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MetricsRec) GetMType() string {
	if x != nil {
		return x.MType
	}
	return ""
}

func (x *MetricsRec) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *MetricsRec) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *MetricsRec            `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_metricsgsv_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetricsRequest) GetMetrics() *MetricsRec {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UpdateMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsResponse) Reset() {
	*x = UpdateMetricsResponse{}
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsResponse) ProtoMessage() {}

func (x *UpdateMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_metricsgsv_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMetricsResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type UpdateMetricsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricsRec          `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsBatchRequest) Reset() {
	*x = UpdateMetricsBatchRequest{}
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsBatchRequest) ProtoMessage() {}

func (x *UpdateMetricsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsBatchRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_metricsgsv_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMetricsBatchRequest) GetMetrics() []*MetricsRec {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UpdateMetricsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"zigzag64,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsBatchResponse) Reset() {
	*x = UpdateMetricsBatchResponse{}
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsBatchResponse) ProtoMessage() {}

func (x *UpdateMetricsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsBatchResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricsBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_metricsgsv_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMetricsBatchResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *MetricsRec            `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_metricsgsv_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetricsRequest) GetMetrics() *MetricsRec {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *MetricsRec            `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metricsgsv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_metricsgsv_proto_rawDescGZIP(), []int{6}
}

func (x *GetMetricsResponse) GetMetrics() *MetricsRec {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_internal_proto_metricsgsv_proto protoreflect.FileDescriptor

const file_internal_proto_metricsgsv_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/metricsgsv.proto\x12\n" +
	"metricsgsv\"^\n" +
	"\n" +
	"MetricsRec\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05MType\x18\x02 \x01(\tR\x05MType\x12\x14\n" +
	"\x05Delta\x18\x03 \x01(\x12R\x05Delta\x12\x14\n" +
	"\x05Value\x18\x04 \x01(\x01R\x05Value\"H\n" +
	"\x14UpdateMetricsRequest\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x16.metricsgsv.MetricsRecR\ametrics\"'\n" +
	"\x15UpdateMetricsResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"M\n" +
	"\x19UpdateMetricsBatchRequest\x120\n" +
	"\ametrics\x18\x01 \x03(\v2\x16.metricsgsv.MetricsRecR\ametrics\"0\n" +
	"\x1aUpdateMetricsBatchResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x12R\x04size\"E\n" +
	"\x11GetMetricsRequest\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x16.metricsgsv.MetricsRecR\ametrics\"F\n" +
	"\x12GetMetricsResponse\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x16.metricsgsv.MetricsRecR\ametrics2\x91\x02\n" +
	"\aMetrics\x12T\n" +
	"\rUpdateMetrics\x12 .metricsgsv.UpdateMetricsRequest\x1a!.metricsgsv.UpdateMetricsResponse\x12c\n" +
	"\x12UpdateMetricsBatch\x12%.metricsgsv.UpdateMetricsBatchRequest\x1a&.metricsgsv.UpdateMetricsBatchResponse\x12K\n" +
	"\n" +
	"GetMetrics\x12\x1d.metricsgsv.GetMetricsRequest\x1a\x1e.metricsgsv.GetMetricsResponseB9Z7github.com/Allegathor/perfmon/internal/proto/metricsgsvb\x06proto3"

var (
	file_internal_proto_metricsgsv_proto_rawDescOnce sync.Once
	file_internal_proto_metricsgsv_proto_rawDescData []byte
)

func file_internal_proto_metricsgsv_proto_rawDescGZIP() []byte {
	file_internal_proto_metricsgsv_proto_rawDescOnce.Do(func() {
		file_internal_proto_metricsgsv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_metricsgsv_proto_rawDesc), len(file_internal_proto_metricsgsv_proto_rawDesc)))
	})
	return file_internal_proto_metricsgsv_proto_rawDescData
}

var file_internal_proto_metricsgsv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_proto_metricsgsv_proto_goTypes = []any{
	(*MetricsRec)(nil),                 // 0: metricsgsv.MetricsRec
	(*UpdateMetricsRequest)(nil),       // 1: metricsgsv.UpdateMetricsRequest
	(*UpdateMetricsResponse)(nil),      // 2: metricsgsv.UpdateMetricsResponse
	(*UpdateMetricsBatchRequest)(nil),  // 3: metricsgsv.UpdateMetricsBatchRequest
	(*UpdateMetricsBatchResponse)(nil), // 4: metricsgsv.UpdateMetricsBatchResponse
	(*GetMetricsRequest)(nil),          // 5: metricsgsv.GetMetricsRequest
	(*GetMetricsResponse)(nil),         // 6: metricsgsv.GetMetricsResponse
}
var file_internal_proto_metricsgsv_proto_depIdxs = []int32{
	0, // 0: metricsgsv.UpdateMetricsRequest.metrics:type_name -> metricsgsv.MetricsRec
	0, // 1: metricsgsv.UpdateMetricsBatchRequest.metrics:type_name -> metricsgsv.MetricsRec
	0, // 2: metricsgsv.GetMetricsRequest.metrics:type_name -> metricsgsv.MetricsRec
	0, // 3: metricsgsv.GetMetricsResponse.metrics:type_name -> metricsgsv.MetricsRec
	1, // 4: metricsgsv.Metrics.UpdateMetrics:input_type -> metricsgsv.UpdateMetricsRequest
	3, // 5: metricsgsv.Metrics.UpdateMetricsBatch:input_type -> metricsgsv.UpdateMetricsBatchRequest
	5, // 6: metricsgsv.Metrics.GetMetrics:input_type -> metricsgsv.GetMetricsRequest
	2, // 7: metricsgsv.Metrics.UpdateMetrics:output_type -> metricsgsv.UpdateMetricsResponse
	4, // 8: metricsgsv.Metrics.UpdateMetricsBatch:output_type -> metricsgsv.UpdateMetricsBatchResponse
	6, // 9: metricsgsv.Metrics.GetMetrics:output_type -> metricsgsv.GetMetricsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_metricsgsv_proto_init() }
func file_internal_proto_metricsgsv_proto_init() {
	if File_internal_proto_metricsgsv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_metricsgsv_proto_rawDesc), len(file_internal_proto_metricsgsv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_metricsgsv_proto_goTypes,
		DependencyIndexes: file_internal_proto_metricsgsv_proto_depIdxs,
		MessageInfos:      file_internal_proto_metricsgsv_proto_msgTypes,
	}.Build()
	File_internal_proto_metricsgsv_proto = out.File
	file_internal_proto_metricsgsv_proto_goTypes = nil
	file_internal_proto_metricsgsv_proto_depIdxs = nil
}
